import type { Metadata } from "next";
import { SITE, absoluteUrl } from "@/lib/site";

/** Primary discovery keywords — used sparingly in metadata, never stuffed into copy. */
export const SEO_KEYWORDS = [
  "AI learning platform",
  "full stack learning platform",
  "AI developer course",
  "software engineering learning platform",
  "developer roadmap",
  "programming learning platform",
  "learn full stack development",
  "learn AI development",
  "AI mentor",
  "developer certification",
  "programming certification",
  "coding platform",
  "developer skills",
  "frontend development",
  "backend development",
  "system design learning",
  "JavaScript course",
  "React course",
  "Next.js course",
  "TypeScript course",
  "developer portfolio projects",
  "real world projects",
  "interview preparation",
  "software engineer training",
  "coding practice",
  "developer career platform",
] as const;

/** Default social preview — generated by `app/opengraph-image.tsx`. */
export const DEFAULT_OG_IMAGE = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: `${SITE.name} — Full Stack & AI Engineering Learning Platform`,
} as const;

export type PageSeoInput = {
  title: string;
  description: string;
  path: string;
  keywords?: string[];
  image?: { url: string; width?: number; height?: number; alt?: string };
  noIndex?: boolean;
  type?: "website" | "article" | "profile";
};

/**
 * Builds consistent Next.js Metadata for public marketing and auth pages.
 */
export function buildPageMetadata({
  title,
  description,
  path,
  keywords = [...SEO_KEYWORDS.slice(0, 12)],
  image = DEFAULT_OG_IMAGE,
  noIndex = false,
  type = "website",
}: PageSeoInput): Metadata {
  const url = absoluteUrl(path);
  const fullTitle = title.includes(SITE.name) ? title : `${title} · ${SITE.name}`;

  return {
    title,
    description,
    keywords: [...keywords],
    alternates: { canonical: url },
    robots: noIndex
      ? {
          index: false,
          follow: false,
          googleBot: { index: false, follow: false },
        }
      : {
          index: true,
          follow: true,
          googleBot: {
            index: true,
            follow: true,
            "max-image-preview": "large",
            "max-snippet": -1,
            "max-video-preview": -1,
          },
        },
    openGraph: {
      type,
      siteName: SITE.name,
      locale: SITE.locale,
      url,
      title: fullTitle,
      description,
      images: [
        {
          url: image.url,
          width: image.width ?? 1200,
          height: image.height ?? 630,
          alt: image.alt ?? SITE.name,
        },
      ],
    },
    twitter: {
      card: "summary_large_image",
      title: fullTitle,
      description,
      images: [image.url],
    },
  };
}

export const PRIVATE_ROBOTS: Metadata["robots"] = {
  index: false,
  follow: false,
  nocache: true,
  googleBot: { index: false, follow: false, noimageindex: true },
};
