export type HtmlDifficulty = "beginner" | "intermediate" | "advanced";

export type HtmlTopicDef = {
  slug: string;
  title: string;
  summary: string;
  estimatedMinutes: number;
  difficulty: HtmlDifficulty;
  keywords: string[];
  /** Challenge weight — higher = more challenges generated */
  challengeWeight: number;
  explanation: string;
  a11yNotes: string[];
  seoNotes: string[];
  commonMistakes: string[];
  bestPractices: string[];
  interviewQuestions: string[];
  cheatSheet: Array<{ tag: string; desc: string }>;
};

export type HtmlSectionDef = {
  slug: string;
  title: string;
  description: string;
  topics: HtmlTopicDef[];
};

function t(
  partial: HtmlTopicDef
): HtmlTopicDef {
  return partial;
}

export const HTML_ACADEMY_SECTIONS: HtmlSectionDef[] = [
  {
    slug: "html-introduction",
    title: "HTML Introduction",
    description: "What HTML is, how browsers render pages, and how it fits the web stack.",
    topics: [
      t({
        slug: "what-is-html",
        title: "What is HTML?",
        summary: "HTML is the structure language of the web — not a programming language.",
        estimatedMinutes: 12,
        difficulty: "beginner",
        keywords: ["html", "markup", "structure"],
        challengeWeight: 4,
        explanation:
          "HTML (HyperText Markup Language) describes the structure and meaning of content in a webpage. Browsers parse HTML into a DOM tree, then apply CSS and JavaScript. You mark up headings, paragraphs, links, forms, and media so machines and people understand the page.",
        a11yNotes: ["Semantic structure helps screen readers navigate."],
        seoNotes: ["Clean structure and headings help crawlers understand topics."],
        commonMistakes: ["Treating HTML as a styling language", "Skipping DOCTYPE"],
        bestPractices: ["Content first, then presentation with CSS", "One clear purpose per page"],
        interviewQuestions: ["Is HTML a programming language?", "What does the browser do with HTML?"],
        cheatSheet: [
          { tag: "<!DOCTYPE html>", desc: "HTML5 document mode" },
          { tag: "<html>", desc: "Root element" },
        ],
      }),
      t({
        slug: "how-browsers-render",
        title: "How Browsers Render Pages",
        summary: "Parse → DOM → CSSOM → render tree → layout → paint.",
        estimatedMinutes: 14,
        difficulty: "beginner",
        keywords: ["browser", "render", "dom", "cssom"],
        challengeWeight: 3,
        explanation:
          "The browser downloads HTML, builds the DOM, fetches CSS/JS, builds CSSOM, combines into a render tree, lays out boxes, then paints pixels. Blocking scripts and huge images delay first paint — which is why performance starts with HTML choices.",
        a11yNotes: ["Fast first contentful paint helps everyone, including assistive tech users."],
        seoNotes: ["Crawlable HTML content beats JS-only critical content."],
        commonMistakes: ["Putting huge scripts in <head> without defer/async"],
        bestPractices: ["Critical content in HTML", "Defer non-critical scripts"],
        interviewQuestions: ["What is the critical rendering path?", "DOM vs CSSOM?"],
        cheatSheet: [{ tag: "DOM", desc: "Document Object Model tree of nodes" }],
      }),
      t({
        slug: "html-with-css-js",
        title: "HTML with CSS and JavaScript",
        summary: "Structure, presentation, and behavior — keep concerns separated.",
        estimatedMinutes: 12,
        difficulty: "beginner",
        keywords: ["css", "javascript", "separation"],
        challengeWeight: 3,
        explanation:
          "HTML = structure/meaning. CSS = look. JavaScript = behavior. Inline styles and onclick handlers work but hurt maintainability, caching, and accessibility. Prefer classes, external stylesheets, and unobtrusive JS.",
        a11yNotes: ["Do not rely on color or hover alone for meaning."],
        seoNotes: ["Meaningful HTML remains if CSS/JS fails."],
        commonMistakes: ["Styling with <font> and align attributes"],
        bestPractices: ["Semantic HTML + CSS classes", "Progressive enhancement"],
        interviewQuestions: ["Why separate HTML/CSS/JS?"],
        cheatSheet: [
          { tag: "<link rel=\"stylesheet\">", desc: "Attach CSS" },
          { tag: "<script defer>", desc: "Non-blocking JS" },
        ],
      }),
      t({
        slug: "client-vs-server",
        title: "Client vs Server",
        summary: "Where HTML is generated and where it runs.",
        estimatedMinutes: 10,
        difficulty: "beginner",
        keywords: ["client", "server", "http"],
        challengeWeight: 2,
        explanation:
          "The client (browser) requests a URL. A server responds with HTML (static file or generated). The browser then may fetch more assets. Understanding this helps you debug caching, SEO, and SSR vs CSR later.",
        a11yNotes: [],
        seoNotes: ["Server-rendered HTML is easiest for crawlers."],
        commonMistakes: ["Assuming HTML always lives only on the client"],
        bestPractices: ["Know your delivery model (static, SSR, SPA)"],
        interviewQuestions: ["What is the difference between client and server?"],
        cheatSheet: [{ tag: "HTTP GET", desc: "Typical page request" }],
      }),
    ],
  },
  {
    slug: "document-structure",
    title: "HTML Document Structure",
    description: "Every professional page starts with a correct document shell.",
    topics: [
      t({
        slug: "doctype-html-head-body",
        title: "DOCTYPE, html, head, body",
        summary: "The skeleton every page needs.",
        estimatedMinutes: 14,
        difficulty: "beginner",
        keywords: ["doctype", "head", "body"],
        challengeWeight: 5,
        explanation:
          "<!DOCTYPE html> puts browsers in standards mode. <html lang=\"en\"> sets language. <head> holds metadata. <body> holds visible content. Missing lang hurts accessibility and translation tools.",
        a11yNotes: ["Always set lang on <html>."],
        seoNotes: ["title and meta description live in head."],
        commonMistakes: ["Content in <head>", "Missing lang"],
        bestPractices: ["One <h1> in body for the page topic", "Valid nesting"],
        interviewQuestions: ["What does DOCTYPE do?", "What belongs in head vs body?"],
        cheatSheet: [
          { tag: "<!DOCTYPE html>", desc: "HTML5" },
          { tag: "<html lang=\"en\">", desc: "Root + language" },
          { tag: "<head> / <body>", desc: "Meta vs content" },
        ],
      }),
      t({
        slug: "meta-viewport-charset",
        title: "meta, charset, viewport",
        summary: "Encoding and mobile-ready documents.",
        estimatedMinutes: 12,
        difficulty: "beginner",
        keywords: ["meta", "charset", "viewport"],
        challengeWeight: 4,
        explanation:
          "<meta charset=\"UTF-8\"> should appear early. viewport meta enables responsive layouts on phones. Other metas: description, robots, theme-color, Open Graph for social previews.",
        a11yNotes: ["Viewport zoom should not be disabled (user-scalable=no hurts a11y)."],
        seoNotes: ["meta description influences search snippets."],
        commonMistakes: ["charset late in head", "disabling zoom"],
        bestPractices: ["charset first 1024 bytes", "viewport width=device-width"],
        interviewQuestions: ["Why is charset important?", "What does viewport meta do?"],
        cheatSheet: [
          { tag: "<meta charset=\"UTF-8\">", desc: "Encoding" },
          { tag: "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">", desc: "Mobile" },
        ],
      }),
      t({
        slug: "title-link-favicon-script",
        title: "title, link, favicon, script",
        summary: "Identity, assets, and scripts in the document head.",
        estimatedMinutes: 12,
        difficulty: "beginner",
        keywords: ["title", "link", "favicon", "script"],
        challengeWeight: 4,
        explanation:
          "<title> appears in tabs and SERPs. <link> connects stylesheets and icons. favicon.ico or SVG icons brand the tab. <script> with defer/async controls load behavior. <noscript> provides fallbacks.",
        a11yNotes: ["Meaningful titles help users with many tabs."],
        seoNotes: ["Unique titles per page; ~50–60 characters."],
        commonMistakes: ["Duplicate titles site-wide", "Blocking scripts without defer"],
        bestPractices: ["Unique title + description", "defer for module scripts"],
        interviewQuestions: ["defer vs async?", "Why unique titles matter?"],
        cheatSheet: [
          { tag: "<title>", desc: "Document title" },
          { tag: "<link rel=\"icon\">", desc: "Favicon" },
          { tag: "<script defer>", desc: "Deferred JS" },
        ],
      }),
    ],
  },
  {
    slug: "text-typography",
    title: "Text & Typography",
    description: "Every text element with meaning, a11y, and SEO impact.",
    topics: [
      t({
        slug: "headings-h1-h6",
        title: "Headings h1–h6",
        summary: "Outline the page for humans and machines.",
        estimatedMinutes: 14,
        difficulty: "beginner",
        keywords: ["h1", "heading", "outline"],
        challengeWeight: 5,
        explanation:
          "Headings create the document outline. Use one primary h1. Do not skip levels for style. Screen readers jump by heading. SEO uses headings as topical signals — not keyword stuffing.",
        a11yNotes: ["Do not skip levels (h2 → h4).", "Do not use headings only for size."],
        seoNotes: ["Clear hierarchy beats multiple h1 spam."],
        commonMistakes: ["Using h tags for font size only"],
        bestPractices: ["Logical outline", "CSS for visual size"],
        interviewQuestions: ["How many h1s should a page have?", "Why not skip heading levels?"],
        cheatSheet: [
          { tag: "<h1>–<h6>", desc: "Heading levels" },
        ],
      }),
      t({
        slug: "paragraphs-inline-text",
        title: "Paragraphs & Inline Text",
        summary: "p, span, strong, em, small, mark, and friends.",
        estimatedMinutes: 14,
        difficulty: "beginner",
        keywords: ["p", "strong", "em", "span"],
        challengeWeight: 5,
        explanation:
          "<p> for paragraphs. <strong> for importance, <em> for emphasis (not just bold/italic). <span> is meaningless — use only for styling hooks. <mark>, <small>, <sup>, <sub>, <abbr>, <time>, <code>, <kbd> carry specific meaning.",
        a11yNotes: ["Prefer semantic emphasis over <b>/<i> alone."],
        seoNotes: ["Meaningful text beats empty spans."],
        commonMistakes: ["<br><br> instead of paragraphs", "span soup"],
        bestPractices: ["Semantic tags first", "span last resort"],
        interviewQuestions: ["strong vs b?", "em vs i?"],
        cheatSheet: [
          { tag: "<p>", desc: "Paragraph" },
          { tag: "<strong> / <em>", desc: "Importance / emphasis" },
          { tag: "<span>", desc: "Hook without meaning" },
        ],
      }),
      t({
        slug: "quotes-code-pre",
        title: "Quotes, Code, and Preformatted Text",
        summary: "blockquote, cite, pre, code, kbd.",
        estimatedMinutes: 12,
        difficulty: "beginner",
        keywords: ["blockquote", "pre", "code"],
        challengeWeight: 3,
        explanation:
          "<blockquote> for long quotations, <q> for short. <cite> for creative work titles. <pre><code> for code samples. <kbd> for keyboard input. Preserve whitespace with pre.",
        a11yNotes: ["Code blocks should still be readable with zoom."],
        seoNotes: [],
        commonMistakes: ["Using pre for layout spacing"],
        bestPractices: ["blockquote + cite when quoting sources"],
        interviewQuestions: ["When do you use blockquote?"],
        cheatSheet: [
          { tag: "<blockquote>", desc: "Long quote" },
          { tag: "<pre><code>", desc: "Code sample" },
        ],
      }),
      t({
        slug: "details-summary-address",
        title: "details, summary, address, time",
        summary: "Disclosure widgets and metadata elements.",
        estimatedMinutes: 12,
        difficulty: "intermediate",
        keywords: ["details", "summary", "time", "address"],
        challengeWeight: 3,
        explanation:
          "<details>/<summary> create native disclosures without JS. <time datetime> machine-readable dates. <address> contact info for the nearest article/body author — not every postal address.",
        a11yNotes: ["details is keyboard accessible by default."],
        seoNotes: ["time helps machines understand dates."],
        commonMistakes: ["Using address for every street address"],
        bestPractices: ["Native details before custom accordion JS"],
        interviewQuestions: ["What is details/summary good for?"],
        cheatSheet: [
          { tag: "<details><summary>", desc: "Disclosure" },
          { tag: "<time datetime>", desc: "Date/time" },
        ],
      }),
    ],
  },
  {
    slug: "links-navigation",
    title: "Links & Navigation",
    description: "Anchors, URLs, navigation patterns, and safe external links.",
    topics: [
      t({
        slug: "anchor-basics",
        title: "Anchor Basics",
        summary: "a href — the hypertext in HyperText.",
        estimatedMinutes: 12,
        difficulty: "beginner",
        keywords: ["a", "href", "link"],
        challengeWeight: 5,
        explanation:
          "<a href> creates hyperlinks. Text should describe the destination (avoid click here). Use relative URLs within a site and absolute for external. Empty href or # placeholders hurt UX and a11y.",
        a11yNotes: ["Descriptive link text", "Visible focus styles"],
        seoNotes: ["Internal linking spreads authority and helps crawl paths."],
        commonMistakes: ["click here", "javascript:void links"],
        bestPractices: ["Clear labels", "Real URLs"],
        interviewQuestions: ["What makes good link text?"],
        cheatSheet: [{ tag: "<a href=\"/about\">About</a>", desc: "Internal link" }],
      }),
      t({
        slug: "link-targets-rel",
        title: "target, rel, download, mailto",
        summary: "Special link behaviors and security.",
        estimatedMinutes: 14,
        difficulty: "intermediate",
        keywords: ["target", "noopener", "mailto", "download"],
        challengeWeight: 4,
        explanation:
          "target=\"_blank\" opens a new tab — always add rel=\"noopener noreferrer\" for security. mailto: and tel: start apps. download suggests a file save. Prefer same-tab navigation for in-app flows.",
        a11yNotes: ["Warn users when opening new tabs when possible."],
        seoNotes: ["External links can use rel=nofollow when appropriate."],
        commonMistakes: ["_blank without noopener"],
        bestPractices: ["noopener noreferrer with _blank"],
        interviewQuestions: ["Why noopener with target=_blank?"],
        cheatSheet: [
          { tag: "rel=\"noopener noreferrer\"", desc: "Safe new tab" },
          { tag: "mailto:", desc: "Email link" },
        ],
      }),
      t({
        slug: "nav-breadcrumbs",
        title: "Navigation & Breadcrumbs",
        summary: "nav landmark and breadcrumb patterns.",
        estimatedMinutes: 12,
        difficulty: "intermediate",
        keywords: ["nav", "breadcrumb"],
        challengeWeight: 4,
        explanation:
          "Wrap primary menus in <nav aria-label>. Breadcrumbs help orientation — use a list of links, mark current page. Skip links help keyboard users jump to main content.",
        a11yNotes: ["aria-current=\"page\" on current crumb", "Skip to content link"],
        seoNotes: ["Breadcrumb structured data is a later enhancement."],
        commonMistakes: ["Multiple navs with no labels"],
        bestPractices: ["Label each nav", "Lists for menus"],
        interviewQuestions: ["Why use nav instead of div?"],
        cheatSheet: [{ tag: "<nav aria-label=\"Primary\">", desc: "Named landmark" }],
      }),
    ],
  },
  {
    slug: "images-media",
    title: "Images & Media",
    description: "img, picture, SVG, performance, and alt text that works.",
    topics: [
      t({
        slug: "img-alt-lazy",
        title: "img, alt, and lazy loading",
        summary: "Every image needs a job: informative or decorative.",
        estimatedMinutes: 14,
        difficulty: "beginner",
        keywords: ["img", "alt", "loading"],
        challengeWeight: 5,
        explanation:
          "alt describes the image for screen readers and when images fail. Decorative images use alt=\"\". loading=\"lazy\" defers offscreen images. width/height reduce layout shift. Never put critical text only inside images.",
        a11yNotes: ["Meaningful alt; empty alt for decoration"],
        seoNotes: ["Descriptive filenames + alt help image search"],
        commonMistakes: ["Missing alt", "alt that says image of…"],
        bestPractices: ["alt describes purpose", "dimensions set"],
        interviewQuestions: ["When is alt empty?", "What is lazy loading?"],
        cheatSheet: [
          { tag: "<img alt=\"…\" loading=\"lazy\">", desc: "Accessible image" },
        ],
      }),
      t({
        slug: "picture-srcset",
        title: "picture, source, and srcset",
        summary: "Responsive images for real devices.",
        estimatedMinutes: 16,
        difficulty: "intermediate",
        keywords: ["picture", "srcset", "sizes"],
        challengeWeight: 4,
        explanation:
          "srcset + sizes let the browser pick a resolution. <picture> chooses art direction or formats (AVIF/WebP with fallbacks). Serve smaller files on mobile — HTML is part of performance.",
        a11yNotes: ["alt still required on img inside picture"],
        seoNotes: ["Faster LCP helps rankings"],
        commonMistakes: ["Huge PNGs for photos"],
        bestPractices: ["Modern formats + fallback img"],
        interviewQuestions: ["picture vs srcset?"],
        cheatSheet: [{ tag: "<picture><source><img></picture>", desc: "Art direction / formats" }],
      }),
      t({
        slug: "figure-svg-icons",
        title: "figure, figcaption, SVG",
        summary: "Captions and scalable graphics.",
        estimatedMinutes: 12,
        difficulty: "intermediate",
        keywords: ["figure", "svg", "icon"],
        challengeWeight: 3,
        explanation:
          "<figure> groups media with optional <figcaption>. Inline SVG is sharp and styleable; decorative SVG needs aria-hidden. Icon buttons need accessible names.",
        a11yNotes: ["SVG icons in buttons need aria-label or text"],
        seoNotes: [],
        commonMistakes: ["Icon-only buttons with no name"],
        bestPractices: ["figure for referenced diagrams"],
        interviewQuestions: ["When use figure?"],
        cheatSheet: [{ tag: "<figure><img><figcaption>", desc: "Captioned media" }],
      }),
    ],
  },
  {
    slug: "lists",
    title: "Lists",
    description: "Ordered, unordered, description lists, and menu patterns.",
    topics: [
      t({
        slug: "ul-ol-li",
        title: "ul, ol, and li",
        summary: "Lists for related items — not for layout.",
        estimatedMinutes: 10,
        difficulty: "beginner",
        keywords: ["ul", "ol", "li"],
        challengeWeight: 4,
        explanation:
          "ul for unordered sets, ol for sequences. Nest carefully. Do not use lists only to indent. Nav menus are often ul inside nav.",
        a11yNotes: ["Lists announce item counts to screen readers"],
        seoNotes: [],
        commonMistakes: ["div stacks instead of lists for related items"],
        bestPractices: ["Real lists for real groups"],
        interviewQuestions: ["ul vs ol?"],
        cheatSheet: [
          { tag: "<ul><li>", desc: "Bullets" },
          { tag: "<ol><li>", desc: "Numbered" },
        ],
      }),
      t({
        slug: "dl-nested-nav-lists",
        title: "Description & Nested Lists",
        summary: "dl/dt/dd and nested navigation structures.",
        estimatedMinutes: 12,
        difficulty: "intermediate",
        keywords: ["dl", "dt", "dd", "nested"],
        challengeWeight: 3,
        explanation:
          "dl pairs terms (dt) with descriptions (dd) — glossaries, metadata. Nested ul/ol build submenus. Keep nesting shallow for clarity.",
        a11yNotes: ["Keep nesting understandable"],
        seoNotes: [],
        commonMistakes: ["Using tables for key/value when dl fits"],
        bestPractices: ["dl for term/definition pairs"],
        interviewQuestions: ["When use dl?"],
        cheatSheet: [{ tag: "<dl><dt><dd>", desc: "Description list" }],
      }),
    ],
  },
  {
    slug: "tables",
    title: "Tables",
    description: "Data tables with accessibility — never for page layout.",
    topics: [
      t({
        slug: "table-basics",
        title: "Table Structure",
        summary: "table, thead, tbody, tfoot, caption.",
        estimatedMinutes: 14,
        difficulty: "intermediate",
        keywords: ["table", "thead", "caption"],
        challengeWeight: 4,
        explanation:
          "Use tables for tabular data only. caption titles the table. thead/tbody/tfoot clarify sections. th with scope helps screen readers associate headers.",
        a11yNotes: ["scope=\"col\" / scope=\"row\"", "Never tables for layout"],
        seoNotes: [],
        commonMistakes: ["Layout tables", "Missing headers"],
        bestPractices: ["caption + th scope"],
        interviewQuestions: ["Why not tables for layout?"],
        cheatSheet: [
          { tag: "<table><caption><thead>", desc: "Accessible data table" },
        ],
      }),
      t({
        slug: "table-a11y-responsive",
        title: "Accessible & Responsive Tables",
        summary: "scope, colgroup, and mobile strategies.",
        estimatedMinutes: 14,
        difficulty: "advanced",
        keywords: ["scope", "colgroup", "responsive table"],
        challengeWeight: 3,
        explanation:
          "Complex tables may need headers attribute. On small screens, overflow scroll wrappers or card transformations (CSS) keep data usable. Always keep header associations.",
        a11yNotes: ["Associate headers correctly"],
        seoNotes: [],
        commonMistakes: ["Unlabeled columns on mobile"],
        bestPractices: ["Test with keyboard + SR"],
        interviewQuestions: ["How do you make tables accessible?"],
        cheatSheet: [{ tag: "scope=\"col\"", desc: "Column header" }],
      }),
    ],
  },
  {
    slug: "forms",
    title: "Forms",
    description: "The deepest HTML skill — every input, validation, and label pattern.",
    topics: [
      t({
        slug: "form-basics-labels",
        title: "form, label, and Controls",
        summary: "Every control needs an accessible name.",
        estimatedMinutes: 16,
        difficulty: "beginner",
        keywords: ["form", "label", "input"],
        challengeWeight: 6,
        explanation:
          "Wrap fields in <form>. Associate <label for> with input id. Placeholders are not labels. Group related controls with fieldset/legend. Buttons should say what they do.",
        a11yNotes: ["Visible labels required", "fieldset for radio groups"],
        seoNotes: [],
        commonMistakes: ["Placeholder-only labels", "Missing for/id"],
        bestPractices: ["label + id pairing", "Clear submit text"],
        interviewQuestions: ["Why are labels required?"],
        cheatSheet: [
          { tag: "<label for=\"email\">", desc: "Label association" },
          { tag: "<fieldset><legend>", desc: "Group" },
        ],
      }),
      t({
        slug: "input-types",
        title: "HTML Input Types",
        summary: "text, email, password, number, date, file, and more.",
        estimatedMinutes: 20,
        difficulty: "intermediate",
        keywords: ["input", "type", "email", "password"],
        challengeWeight: 8,
        explanation:
          "type changes keyboard, validation, and mobile UX: email, tel, url, number, date, time, range, color, file, hidden, checkbox, radio, search. Pick the most specific type that fits.",
        a11yNotes: ["Error messages linked via aria-describedby"],
        seoNotes: [],
        commonMistakes: ["Everything as type=text"],
        bestPractices: ["Correct type for correct keyboard"],
        interviewQuestions: ["Name five useful input types"],
        cheatSheet: [
          { tag: "type=\"email\"", desc: "Email field" },
          { tag: "type=\"password\"", desc: "Masked input" },
        ],
      }),
      t({
        slug: "select-textarea-buttons",
        title: "select, textarea, and Buttons",
        summary: "Long text, dropdowns, and submit patterns.",
        estimatedMinutes: 14,
        difficulty: "beginner",
        keywords: ["select", "textarea", "button"],
        challengeWeight: 5,
        explanation:
          "textarea for multi-line text. select/option/optgroup for choices. Prefer button type=submit inside forms. Avoid resetting forms casually — users lose work.",
        a11yNotes: ["optgroup needs label"],
        seoNotes: [],
        commonMistakes: ["div click handlers instead of buttons"],
        bestPractices: ["Native controls first"],
        interviewQuestions: ["button vs input type=submit?"],
        cheatSheet: [
          { tag: "<textarea>", desc: "Multi-line" },
          { tag: "<select><option>", desc: "Dropdown" },
        ],
      }),
      t({
        slug: "form-validation",
        title: "Native Validation",
        summary: "required, pattern, min, max, step, autocomplete.",
        estimatedMinutes: 16,
        difficulty: "intermediate",
        keywords: ["required", "pattern", "autocomplete"],
        challengeWeight: 6,
        explanation:
          "HTML constraint validation: required, minlength/maxlength, min/max/step, pattern, type mismatches. autocomplete improves UX and password managers. novalidate when you fully own client validation — rare.",
        a11yNotes: ["Do not rely on color alone for errors"],
        seoNotes: [],
        commonMistakes: ["Disabling validation without replacements"],
        bestPractices: ["autocomplete tokens", "Helpful error text"],
        interviewQuestions: ["What does required do?", "Why autocomplete matters?"],
        cheatSheet: [
          { tag: "required", desc: "Must fill" },
          { tag: "pattern", desc: "Regex constraint" },
          { tag: "autocomplete=\"email\"", desc: "Autofill hint" },
        ],
      }),
    ],
  },
  {
    slug: "semantic-html",
    title: "Semantic HTML",
    description: "Landmarks and sectioning that make sites maintainable and accessible.",
    topics: [
      t({
        slug: "landmarks-header-main-footer",
        title: "header, main, footer, nav",
        summary: "Page landmarks every site should have.",
        estimatedMinutes: 14,
        difficulty: "beginner",
        keywords: ["header", "main", "footer", "nav"],
        challengeWeight: 5,
        explanation:
          "header/footer can appear in page or section scope. main is unique per page — primary content. nav for navigation blocks. These landmarks let assistive tech jump efficiently.",
        a11yNotes: ["One main", "Label multiple navs"],
        seoNotes: ["Clear main content helps understand page topic"],
        commonMistakes: ["Multiple main", "div-only layouts"],
        bestPractices: ["Landmark skeleton first"],
        interviewQuestions: ["How many main elements?"],
        cheatSheet: [
          { tag: "<header> <nav> <main> <footer>", desc: "Page shell" },
        ],
      }),
      t({
        slug: "section-article-aside",
        title: "section, article, aside",
        summary: "Thematic grouping vs standalone content.",
        estimatedMinutes: 14,
        difficulty: "intermediate",
        keywords: ["section", "article", "aside"],
        challengeWeight: 5,
        explanation:
          "article is independently distributable (post, card). section is a thematic group with a heading. aside is tangentially related. Prefer these over anonymous divs when meaning exists.",
        a11yNotes: ["Sections need headings"],
        seoNotes: ["Articles map well to content units"],
        commonMistakes: ["section without heading", "article for every div"],
        bestPractices: ["Meaning-driven tags"],
        interviewQuestions: ["article vs section?"],
        cheatSheet: [
          { tag: "<article>", desc: "Standalone piece" },
          { tag: "<section>", desc: "Thematic group" },
          { tag: "<aside>", desc: "Related aside" },
        ],
      }),
      t({
        slug: "dialog-and-semantics",
        title: "dialog and Modern Semantics",
        summary: "Native dialog and when semantics beat div soup.",
        estimatedMinutes: 12,
        difficulty: "advanced",
        keywords: ["dialog", "semantic"],
        challengeWeight: 3,
        explanation:
          "<dialog> provides native modal/non-modal dialogs with better baseline accessibility than DIY div overlays. Prefer native elements before ARIA widget recreations.",
        a11yNotes: ["Prefer native dialog focus management"],
        seoNotes: [],
        commonMistakes: ["Custom modals without focus trap"],
        bestPractices: ["Native first, ARIA second"],
        interviewQuestions: ["Why prefer semantic HTML over ARIA?"],
        cheatSheet: [{ tag: "<dialog>", desc: "Native dialog" }],
      }),
    ],
  },
  {
    slug: "accessibility",
    title: "Accessibility",
    description: "Build for keyboard, screen readers, and inclusive UX.",
    topics: [
      t({
        slug: "a11y-fundamentals",
        title: "Accessibility Fundamentals",
        summary: "Perceivable, operable, understandable, robust (POUR).",
        estimatedMinutes: 16,
        difficulty: "intermediate",
        keywords: ["a11y", "wcag", "keyboard"],
        challengeWeight: 5,
        explanation:
          "Accessibility is not optional polish — it is correct HTML. Keyboard access, focus visibility, labels, contrast, and semantics cover most issues. Fix structure before bolting on ARIA.",
        a11yNotes: ["Focus must be visible", "All controls keyboard reachable"],
        seoNotes: ["Accessible sites often have clearer structure for crawlers too"],
        commonMistakes: ["outline:none without replacement"],
        bestPractices: ["Semantic first", "Test with keyboard"],
        interviewQuestions: ["What is WCAG?", "Name four POUR principles"],
        cheatSheet: [{ tag: "Tab / Shift+Tab", desc: "Keyboard navigation" }],
      }),
      t({
        slug: "aria-roles-labels",
        title: "ARIA Roles & Labels",
        summary: "When HTML is not enough — use ARIA carefully.",
        estimatedMinutes: 16,
        difficulty: "advanced",
        keywords: ["aria", "role", "aria-label"],
        challengeWeight: 5,
        explanation:
          "First rule of ARIA: do not use ARIA if a native element works. aria-label, aria-labelledby, aria-describedby name and describe. roles change announced semantics — misuse causes harm.",
        a11yNotes: ["No ARIA is better than bad ARIA"],
        seoNotes: [],
        commonMistakes: ["role=button on div instead of <button>"],
        bestPractices: ["Native elements first"],
        interviewQuestions: ["First rule of ARIA?"],
        cheatSheet: [
          { tag: "aria-label", desc: "Accessible name" },
          { tag: "aria-labelledby", desc: "Name from element ids" },
        ],
      }),
      t({
        slug: "a11y-audit-practice",
        title: "Accessibility Audit Practice",
        summary: "Find and fix real markup issues.",
        estimatedMinutes: 18,
        difficulty: "advanced",
        keywords: ["audit", "fix", "a11y"],
        challengeWeight: 4,
        explanation:
          "Audits check: missing labels, bad alt, skipped headings, unlabeled buttons, low contrast (CSS), missing lang, keyboard traps. Practice fixing broken HTML snippets until patterns stick.",
        a11yNotes: ["Fix one issue class at a time"],
        seoNotes: [],
        commonMistakes: ["Ignoring keyboard testing"],
        bestPractices: ["Manual + automated checks"],
        interviewQuestions: ["How would you audit a page for a11y?"],
        cheatSheet: [{ tag: "Checklist", desc: "labels, alt, headings, focus, lang" }],
      }),
    ],
  },
  {
    slug: "seo-basics",
    title: "SEO Basics",
    description: "Titles, metas, headings, and crawl-friendly HTML.",
    topics: [
      t({
        slug: "seo-title-description",
        title: "Title & Meta Description",
        summary: "SERP identity starts in the head.",
        estimatedMinutes: 12,
        difficulty: "intermediate",
        keywords: ["seo", "title", "description"],
        challengeWeight: 4,
        explanation:
          "Unique title and meta description per page. Titles carry primary topic; descriptions market the click. Avoid duplicates and keyword stuffing.",
        a11yNotes: ["Good titles help all users"],
        seoNotes: ["Unique metadata site-wide"],
        commonMistakes: ["Same title on every page"],
        bestPractices: ["Primary keyword near start of title"],
        interviewQuestions: ["What belongs in title vs h1?"],
        cheatSheet: [
          { tag: "<title>", desc: "SERP title" },
          { tag: "<meta name=\"description\">", desc: "Snippet hint" },
        ],
      }),
      t({
        slug: "seo-structure-og",
        title: "Structure, Canonical, Open Graph",
        summary: "Canonical URLs and social previews.",
        estimatedMinutes: 14,
        difficulty: "advanced",
        keywords: ["canonical", "opengraph", "robots"],
        challengeWeight: 4,
        explanation:
          "Canonical hints the preferred URL. Open Graph / Twitter meta tags control social cards. robots meta can control indexing. HTML structure (headings, links) remains the foundation.",
        a11yNotes: [],
        seoNotes: ["Canonical for duplicate content cases"],
        commonMistakes: ["Blocking important pages in robots"],
        bestPractices: ["One clear canonical strategy"],
        interviewQuestions: ["What does rel=canonical do?"],
        cheatSheet: [
          { tag: "<link rel=\"canonical\">", desc: "Preferred URL" },
          { tag: "og:title / og:image", desc: "Social preview" },
        ],
      }),
    ],
  },
  {
    slug: "embedding-content",
    title: "Embedding Content",
    description: "iframe, audio, video, and third-party embeds.",
    topics: [
      t({
        slug: "audio-video-track",
        title: "audio, video, source, track",
        summary: "Native media with captions.",
        estimatedMinutes: 14,
        difficulty: "intermediate",
        keywords: ["video", "audio", "track"],
        challengeWeight: 4,
        explanation:
          "Native <video> and <audio> with multiple <source> formats. <track kind=\"captions\"> is essential for accessibility. Controls, poster, and preload affect UX and performance.",
        a11yNotes: ["Captions/subtitles required for video content"],
        seoNotes: ["Transcripts help discoverability"],
        commonMistakes: ["Autoplay with sound"],
        bestPractices: ["Captions + controls"],
        interviewQuestions: ["How do you caption video in HTML?"],
        cheatSheet: [
          { tag: "<video controls>", desc: "Video player" },
          { tag: "<track kind=\"captions\">", desc: "Captions" },
        ],
      }),
      t({
        slug: "iframe-embeds",
        title: "iframe & Third-party Embeds",
        summary: "Maps, YouTube, and sandboxing.",
        estimatedMinutes: 12,
        difficulty: "intermediate",
        keywords: ["iframe", "embed", "sandbox"],
        challengeWeight: 3,
        explanation:
          "iframes embed other documents. Use title for a11y. sandbox and allow attributes limit risk. Lazy-load heavy embeds when possible. Prefer privacy-enhanced YouTube embeds.",
        a11yNotes: ["iframe needs title"],
        seoNotes: ["Important content should not live only in iframes"],
        commonMistakes: ["Untitled iframes"],
        bestPractices: ["title + sandbox thoughtfully"],
        interviewQuestions: ["Why title an iframe?"],
        cheatSheet: [{ tag: "<iframe title=\"…\">", desc: "Accessible embed" }],
      }),
    ],
  },
  {
    slug: "responsive-html",
    title: "Responsive HTML",
    description: "Viewport, responsive images, and content-first structure.",
    topics: [
      t({
        slug: "responsive-foundations",
        title: "Responsive Foundations",
        summary: "Viewport and content that reflows.",
        estimatedMinutes: 12,
        difficulty: "intermediate",
        keywords: ["responsive", "viewport"],
        challengeWeight: 4,
        explanation:
          "Responsive design starts with viewport meta and fluid content structure. Prefer logical document order. Avoid fixed pixel traps in HTML attributes when CSS can adapt.",
        a11yNotes: ["Do not disable zoom"],
        seoNotes: ["Mobile-friendly pages are expected"],
        commonMistakes: ["No viewport meta"],
        bestPractices: ["Content-first order"],
        interviewQuestions: ["What does the viewport meta tag do?"],
        cheatSheet: [{ tag: "viewport meta", desc: "Mobile layout basis" }],
      }),
      t({
        slug: "responsive-media-html",
        title: "Responsive Media in HTML",
        summary: "picture/srcset in real layouts.",
        estimatedMinutes: 12,
        difficulty: "intermediate",
        keywords: ["srcset", "sizes"],
        challengeWeight: 3,
        explanation:
          "Combine semantic structure with responsive images so mobile users download appropriate assets. HTML choices directly affect Core Web Vitals.",
        a11yNotes: ["Keep alt meaningful across breakpoints"],
        seoNotes: ["Performance is an SEO factor"],
        commonMistakes: ["One huge hero image for all devices"],
        bestPractices: ["srcset for photos", "picture for art direction"],
        interviewQuestions: ["How do you serve responsive images?"],
        cheatSheet: [{ tag: "srcset + sizes", desc: "Resolution switching" }],
      }),
    ],
  },
  {
    slug: "performance",
    title: "Performance",
    description: "HTML decisions that speed up real sites.",
    topics: [
      t({
        slug: "html-performance",
        title: "HTML Performance Practices",
        summary: "Resource hints, lazy media, lean markup.",
        estimatedMinutes: 14,
        difficulty: "advanced",
        keywords: ["performance", "preload", "lazy"],
        challengeWeight: 3,
        explanation:
          "Reduce DOM weight, defer scripts, lazy-load below-fold media, preload critical assets carefully, and keep HTML readable. Bloated markup slows parsing and hydration later.",
        a11yNotes: ["Performance helps assistive tech and slow networks"],
        seoNotes: ["LCP/INP/CLS matter"],
        commonMistakes: ["Preloading everything"],
        bestPractices: ["Measure, then optimize"],
        interviewQuestions: ["How can HTML affect LCP?"],
        cheatSheet: [
          { tag: "loading=\"lazy\"", desc: "Defer offscreen images" },
          { tag: "<link rel=\"preload\">", desc: "Critical resource hint" },
        ],
      }),
    ],
  },
  {
    slug: "best-practices",
    title: "Best Practices",
    description: "Professional conventions for maintainable HTML.",
    topics: [
      t({
        slug: "html-conventions",
        title: "Professional HTML Conventions",
        summary: "Naming, folders, validation, maintainability.",
        estimatedMinutes: 12,
        difficulty: "intermediate",
        keywords: ["best practices", "naming", "structure"],
        challengeWeight: 3,
        explanation:
          "Validate markup, keep indentation consistent, use lowercase element names, quote attributes, prefer data-* for custom hooks, organize assets clearly, and document component HTML patterns for your team.",
        a11yNotes: ["Conventions that include a11y checks"],
        seoNotes: ["Consistent templates improve metadata quality"],
        commonMistakes: ["Inconsistent attribute quoting"],
        bestPractices: ["Validate + review"],
        interviewQuestions: ["What makes maintainable HTML?"],
        cheatSheet: [{ tag: "Validator", desc: "W3C / browser tooling" }],
      }),
    ],
  },
  {
    slug: "interview-preparation",
    title: "Interview Preparation",
    description: "MCQs, scenarios, and senior-level HTML questions.",
    topics: [
      t({
        slug: "html-interview-core",
        title: "Core Interview Questions",
        summary: "Tags, semantics, and practical tradeoffs.",
        estimatedMinutes: 16,
        difficulty: "intermediate",
        keywords: ["interview", "mcq"],
        challengeWeight: 5,
        explanation:
          "Interviewers test whether you understand semantics, forms, a11y, and performance — not memorizing every obscure tag. Practice explaining why you chose elements.",
        a11yNotes: ["Expect a11y questions on modern teams"],
        seoNotes: ["Expect basic SEO/meta questions"],
        commonMistakes: ["Buzzwords without examples"],
        bestPractices: ["Answer with a tiny HTML example"],
        interviewQuestions: ["Explain semantic HTML", "How do forms stay accessible?"],
        cheatSheet: [{ tag: "Explain why", desc: "Always justify element choice" }],
      }),
      t({
        slug: "html-interview-senior",
        title: "Senior Frontend HTML Questions",
        summary: "Architecture, a11y audits, and HTML in design systems.",
        estimatedMinutes: 16,
        difficulty: "advanced",
        keywords: ["senior", "interview"],
        challengeWeight: 4,
        explanation:
          "Senior questions probe design-system markup, accessibility ownership, SEO collaboration, and how HTML choices affect CSS/JS complexity. Be ready to review broken markup.",
        a11yNotes: ["Own accessibility outcomes"],
        seoNotes: ["Partner with content/SEO early"],
        commonMistakes: ["Delegating all a11y to QA"],
        bestPractices: ["Review HTML in PRs"],
        interviewQuestions: ["How do you review HTML in a PR?"],
        cheatSheet: [{ tag: "PR checklist", desc: "semantics, a11y, SEO, perf" }],
      }),
    ],
  },
  {
    slug: "mini-projects",
    title: "Mini Projects",
    description: "Ship realistic pages with pure HTML structure.",
    topics: [
      t({
        slug: "project-resume",
        title: "Project: Resume",
        summary: "Semantic personal resume page.",
        estimatedMinutes: 25,
        difficulty: "intermediate",
        keywords: ["project", "resume"],
        challengeWeight: 3,
        explanation: "Build a resume with header, contact, sections for experience/education/skills, lists, and accessible structure.",
        a11yNotes: ["Heading outline for sections"],
        seoNotes: ["Clear title with your name"],
        commonMistakes: ["Tables for layout"],
        bestPractices: ["Semantic sections"],
        interviewQuestions: [],
        cheatSheet: [{ tag: "header/main/section", desc: "Resume shell" }],
      }),
      t({
        slug: "project-portfolio",
        title: "Project: Portfolio",
        summary: "Projects grid with semantic cards.",
        estimatedMinutes: 25,
        difficulty: "intermediate",
        keywords: ["portfolio", "project"],
        challengeWeight: 3,
        explanation: "Portfolio landing with nav, hero, project articles, and contact form.",
        a11yNotes: ["Project images need alt"],
        seoNotes: ["Unique title"],
        commonMistakes: ["Empty links"],
        bestPractices: ["article per project"],
        interviewQuestions: [],
        cheatSheet: [{ tag: "<article>", desc: "Project card" }],
      }),
      t({
        slug: "project-landing",
        title: "Project: Landing & Marketing Pages",
        summary: "Restaurant / company / pricing / FAQ patterns.",
        estimatedMinutes: 30,
        difficulty: "intermediate",
        keywords: ["landing", "pricing", "faq"],
        challengeWeight: 4,
        explanation: "Marketing pages: hero, features, pricing table, FAQ details/summary, and CTA forms — all semantic.",
        a11yNotes: ["FAQ with details/summary"],
        seoNotes: ["H1 matches campaign topic"],
        commonMistakes: ["Fake buttons as divs"],
        bestPractices: ["Real button/a elements"],
        interviewQuestions: [],
        cheatSheet: [{ tag: "<details>", desc: "FAQ item" }],
      }),
      t({
        slug: "project-blog-docs",
        title: "Project: Blog, News, Docs",
        summary: "Content-heavy layouts with articles and navigation.",
        estimatedMinutes: 28,
        difficulty: "advanced",
        keywords: ["blog", "docs", "news"],
        challengeWeight: 3,
        explanation: "Article pages with header, byline time, content sections, aside related links, and footer — practice long-form semantics.",
        a11yNotes: ["Skip link to article"],
        seoNotes: ["One h1 article title"],
        commonMistakes: ["No time/author semantics"],
        bestPractices: ["article + time"],
        interviewQuestions: [],
        cheatSheet: [{ tag: "<article><time>", desc: "Post metadata" }],
      }),
    ],
  },
  {
    slug: "final-project",
    title: "Final Project",
    description: "Production-ready multipage site with only HTML.",
    topics: [
      t({
        slug: "final-multipage-site",
        title: "Final: Multipage Website",
        summary: "Nav, semantics, forms, tables, media, SEO, a11y.",
        estimatedMinutes: 60,
        difficulty: "advanced",
        keywords: ["final", "multipage", "capstone"],
        challengeWeight: 5,
        explanation:
          "Ship a small multipage website: Home, About, Services, Contact. Include semantic layout, navigation, images with alt, a data table, a validated contact form, meta tags, and accessibility checks. HTML only — structure must stand alone.",
        a11yNotes: ["Landmarks, labels, alt, lang, focusable controls"],
        seoNotes: ["Unique titles/descriptions per page"],
        commonMistakes: ["Single endless page with no structure"],
        bestPractices: ["Checklist before submit"],
        interviewQuestions: ["Walk through your final site structure"],
        cheatSheet: [{ tag: "Pages", desc: "index, about, services, contact" }],
      }),
    ],
  },
];

export function flattenHtmlTopics(): HtmlTopicDef[] {
  return HTML_ACADEMY_SECTIONS.flatMap((s) => s.topics);
}

export function findHtmlTopic(
  slug: string
): { section: HtmlSectionDef; topic: HtmlTopicDef } | null {
  for (const section of HTML_ACADEMY_SECTIONS) {
    const topic = section.topics.find((t) => t.slug === slug);
    if (topic) return { section, topic };
  }
  return null;
}

export function htmlTopicCount(): number {
  return flattenHtmlTopics().length;
}

export function htmlSectionCount(): number {
  return HTML_ACADEMY_SECTIONS.length;
}
